CREATE TABLE `RESOLVER`.`ORGANIZATION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `MOBILE_NUMBER` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE,
  UNIQUE INDEX `MOBILE_NUMBER_UNIQUE` (`MOBILE_NUMBER` ASC) VISIBLE
);

CREATE TABLE `RESOLVER`.`EMPLOYEE` (
  `EMPID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `USERNAME` VARCHAR(45) NOT NULL,
  `MOBILE_NUMBER` VARCHAR(45) NOT NULL,
  `ROLE` VARCHAR(45) NULL,
  `ORGANIZATION_ID` INT NULL,
  PRIMARY KEY (`EMPID`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE,
  UNIQUE INDEX `MOBILE_NUMBER_UNIQUE` (`MOBILE_NUMBER` ASC) VISIBLE,
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC) VISIBLE,
  INDEX `ORGANIZATION_ID_IDX` (`ORGANIZATION_ID` ASC) VISIBLE,
  CONSTRAINT `ORGANIZATION_ID` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `RESOLVER`.`ORGANIZATION` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

);

CREATE TABLE `RESOLVER`.`PROJECT` (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `START_DATE` DATETIME NOT NULL,
  `END_DATE` DATETIME NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  `ORGANIZATION_ID` INT NULL,
  PRIMARY KEY (`PID`),
  INDEX `ORGANIZATION_ID_IDX` (`ORGANIZATION_ID` ASC) VISIBLE,
  CONSTRAINT `PROJECT_ORGANIZATION_ID` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `RESOLVER`.`ORGANIZATION` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

);

CREATE TABLE `RESOLVER`.`TICKET` (
  `TID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `SUMMARY` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `PRIORITY` VARCHAR(45) NOT NULL,
  `RAISED_DATE` DATETIME NOT NULL,
  `CLOSE_DATE` DATETIME NULL,
  `PROJECT_ID` INT NULL,
  `STATUS` VARCHAR(45) NOT NULL DEFAULT 'open',
  PRIMARY KEY (`TID`),
  INDEX `TICKET_PROJECT_ID_IDX` (`PROJECT_ID` ASC) VISIBLE,
  CONSTRAINT `TICKET_PROJECT_ID` FOREIGN KEY (`PROJECT_ID`) REFERENCES `RESOLVER`.`PROJECT` (`PID`) ON DELETE CASCADE ON UPDATE CASCADE;

);

CREATE TABLE `RESOLVER`.`PROJECT_ASSIGN` (
  `ASSIGN_ID` INT NOT NULL AUTO_INCREMENT,
  `PID` INT NULL,
  `EID` INT NULL,
  `ASSIGNED_ON` DATETIME NULL,
  PRIMARY KEY (`ASSIGN_ID`),
  INDEX `ASSIGN_PROJECT_ID_IDX` (`PID` ASC) VISIBLE,
  INDEX `ASSIGN_EMPLOYEE_ID_IDX` (`EID` ASC) VISIBLE,
  CONSTRAINT `ASSIGN_PROJECT_ID` FOREIGN KEY (`PID`) REFERENCES `RESOLVER`.`PROJECT` (`PID`) ON DELETE CASCADE ON UPDATE CASCADE;

,

CONSTRAINT `ASSIGN_EMPLOYEE_ID`

FOREIGN KEY (`EID`)

REFERENCES `RESOLVER`.`EMPLOYEE` (`EMPID`)

ON DELETE CASCADE

ON UPDATE CASCADE;

);

CREATE TABLE `RESOLVER`.`TICKETDETAILS` (
  `TDID` INT NOT NULL AUTO_INCREMENT,
  `DESC` VARCHAR(120) NOT NULL,
  `POSTEDAT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `GENERATEDBY` INT NOT NULL,
  `TID` INT NOT NULL,
  PRIMARY KEY (`TDID`),
  INDEX `GENERATED_BY_IDX` (`GENERATEDBY` ASC) VISIBLE,
  INDEX `TICKET_ID_IDX` (`TID` ASC) VISIBLE,
  CONSTRAINT `GENERATED_BY` FOREIGN KEY (`GENERATEDBY`) REFERENCES `RESOLVER`.`EMPLOYEE` (`EMPID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `TICKET_ID` FOREIGN KEY (`TID`) REFERENCES `RESOLVER`.`TICKET` (`TID`) ON DELETE CASCADE ON UPDATE CASCADE
);